import { defineType, defineField } from "sanity";

export const contactSection = defineType({
  name: "contactSection",
  title: "Sekcja Kontakt",
  type: "document",
  groups: [
    { name: "heading", title: "Nagłówek" },
    { name: "people", title: "Osoby kontaktowe" },
    { name: "form", title: "Formularz" },
  ],
  fields: [
    defineField({
      name: "headingPl",
      title: "Nagłówek (Polski)",
      type: "string",
      group: "heading",
      initialValue: "Kontakt",
    }),
    defineField({
      name: "headingEn",
      title: "Nagłówek (English)",
      type: "string",
      group: "heading",
      initialValue: "Contact",
    }),
    defineField({
      name: "subtitlePl",
      title: "Podtytuł (Polski)",
      type: "string",
      group: "heading",
      initialValue: "Skontaktuj się z nami i zbudujmy coś razem",
    }),
    defineField({
      name: "subtitleEn",
      title: "Podtytuł (English)",
      type: "string",
      group: "heading",
      initialValue: "Get in touch and let's build something together",
    }),
    defineField({
      name: "people",
      title: "Osoby kontaktowe",
      type: "array",
      group: "people",
      of: [
        {
          type: "object",
          name: "contactPerson",
          title: "Osoba",
          fields: [
            { name: "image", title: "Zdjęcie", type: "image", options: { hotspot: true } },
            { name: "namePl", title: "Imię i nazwisko (Polski)", type: "string" },
            { name: "nameEn", title: "Imię i nazwisko (English)", type: "string" },
            { name: "rolePl", title: "Stanowisko (Polski)", type: "string" },
            { name: "roleEn", title: "Stanowisko (English)", type: "string" },
            { name: "email", title: "Email", type: "string" },
            { name: "bioPl", title: "Opis / Bio (Polski)", type: "text" },
            { name: "bioEn", title: "Opis / Bio (English)", type: "text" },
          ],
          preview: {
            select: { title: "namePl" },
          },
        },
      ],
    }),
    defineField({
      name: "nameLabelPl",
      title: "Etykieta Imię (Polski)",
      type: "string",
      group: "form",
      initialValue: "Imię",
    }),
    defineField({
      name: "nameLabelEn",
      title: "Etykieta Imię (English)",
      type: "string",
      group: "form",
      initialValue: "Name",
    }),
    defineField({
      name: "companyLabelPl",
      title: "Etykieta Firma (Polski)",
      type: "string",
      group: "form",
      initialValue: "Nazwa firmy",
    }),
    defineField({
      name: "companyLabelEn",
      title: "Etykieta Firma (English)",
      type: "string",
      group: "form",
      initialValue: "Company name",
    }),
    defineField({
      name: "messageLabelPl",
      title: "Etykieta Opis produktu (Polski)",
      type: "string",
      group: "form",
      initialValue: "Opisz krótko jaki produkt chcesz z nami zbudować?",
    }),
    defineField({
      name: "messageLabelEn",
      title: "Etykieta Opis produktu (English)",
      type: "string",
      group: "form",
      initialValue: "Briefly describe what product you want to build with us?",
    }),
    defineField({
      name: "submitButtonPl",
      title: "Przycisk wyślij (Polski)",
      type: "string",
      group: "form",
      initialValue: "Wyślij wiadomość",
    }),
    defineField({
      name: "submitButtonEn",
      title: "Przycisk wyślij (English)",
      type: "string",
      group: "form",
      initialValue: "Send message",
    }),
    defineField({
      name: "successMessagePl",
      title: "Komunikat sukcesu (Polski)",
      type: "string",
      group: "form",
    }),
    defineField({
      name: "successMessageEn",
      title: "Komunikat sukcesu (English)",
      type: "string",
      group: "form",
    }),
    defineField({
      name: "errorMessagePl",
      title: "Komunikat błędu (Polski)",
      type: "string",
      group: "form",
    }),
    defineField({
      name: "errorMessageEn",
      title: "Komunikat błędu (English)",
      type: "string",
      group: "form",
    }),
    defineField({
      name: "requiredErrorPl",
      title: "Błąd: pole wymagane (Polski)",
      type: "string",
      group: "form",
      initialValue: "To pole jest wymagane",
    }),
    defineField({
      name: "requiredErrorEn",
      title: "Błąd: pole wymagane (English)",
      type: "string",
      group: "form",
      initialValue: "This field is required",
    }),
    defineField({
      name: "invalidEmailPl",
      title: "Błąd: nieprawidłowy email (Polski)",
      type: "string",
      group: "form",
      initialValue: "Podaj prawidłowy adres email",
    }),
    defineField({
      name: "invalidEmailEn",
      title: "Błąd: nieprawidłowy email (English)",
      type: "string",
      group: "form",
      initialValue: "Please enter a valid email address",
    }),
  ],
});
